const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export {ALL_PRODUCT_REQUEST, ALL_PRODUCT_SUCCESS, ALL_PRODUCT_FAIL};